default: &default
  adapter: postgresql 
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: plae_development 
  username: plae

test:
  <<: *default
  database: plae_test
  username: plae

production:
  <<: *default
  database: plae_production
  username: plae
